import type { Metadata } from "next";
import { Kite_One, Contrail_One } from "next/font/google";

import "../styles/globals.css";
import { Providers } from "./Providers";
import Header from "@/layouts/Header/Header";
import Footer from "@/layouts/Footer";

const kiteone = Kite_One({
  subsets: ["latin"],
  variable: "--font-primary",
  weight: ["400"],
});

const contrailOne = Contrail_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-secondary",
});

export const metadata: Metadata = {
  title: "Jasper Supplies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${contrailOne.variable} ${kiteone.className} antialiased`}
      >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
